server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: EcommerceApp
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password:
    locations: classpath:db/migration
